[package]
name = "pageos-core"
version = "0.2.0"
authors = ["PJ568 <pj568@pj568.eu.org>"]
edition = "2024"
description = "构建以浏览器为核心的 Linux 发行版的核心框架"
license = "MPL-2.0"

[dependencies]
warp = "0.3"
tokio = { version = "1", features = ["full"] }
home = "0.5"
